### PR TITLE
Fix Notification Save for Sub Twilio Accounts

### PR DESCRIPTION
**Pull request by AsaadQ**
For some reason, notifications for voicemail and sms don't save (the 2 checkboxes) for sub accounts (site.com/company) unless i comment this section out.

### CODE REVIEW

**Comment by Gipetto** [comment]
Yeah, I can see how this would have a negative effect on those settings. This is the wrong solution though. I'll work up a proper solution.

**Comment by Gipetto** [comment]
Lemme back-track that a bit. I shouldn't say that this is wrong, but its incomplete. We need to guard against those parameters not being set.

**Comment by AsaadQ** [comment]
Ok, i was lucky to get my install working by commenting these out, i am still not 100% sure how it works, so hopefully you can come up with a permanent fix.

**Comment by Gipetto** [comment]
It was a lazy way of figuring out what settings screen was being saved so that it could properly handle the checkboxes since unchecked checkboxes don't show up in `$_POST`.

I'm able to build on some work that I just did, thankfully. Here's the fix: https://github.com/twilio/OpenVBX/commit/0ea5c68a9a7ed67b8c816b463573fc553ec26e8e - the fix is currently only in the develop branch. If this looks good then I might do a release later today.

**Pull request closed without merging**
